// <auto-generated />
using System;
using System.Collections.Generic;
using MenteSaudavel.Server._02.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenteSaudavel.Server._02.Services.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<Guid>("RespondenteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RespondenteId");

                    b.ToTable("Questionario", (string)null);
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Resposta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Valor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Resposta", (string)null);
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "MenteSaudavel.Server._03.Data.Entities.Usuario.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Genero", "MenteSaudavel.Server._03.Data.Entities.Usuario.Genero#Genero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Genero");
                        });

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.HasOne("MenteSaudavel.Server._03.Data.Entities.Usuario", "Respondente")
                        .WithMany("Questionarios")
                        .HasForeignKey("RespondenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MenteSaudavel.Server._03.Data.ValueObjects.Estratificacao", "Estratificacao", b1 =>
                        {
                            b1.Property<Guid>("QuestionarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Estratificacao");

                            b1.HasKey("QuestionarioId");

                            b1.ToTable("Questionario", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuestionarioId");
                        });

                    b.Navigation("Estratificacao");

                    b.Navigation("Respondente");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Resposta", b =>
                {
                    b.HasOne("MenteSaudavel.Server._03.Data.Entities.Questionario", "Questionario")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Questionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
